// AUTO-GENERATED by scripts/build-demo-snapshot.ts.
// Ships EMPTY: while DEMO_DISHES is empty, every /demo route 404s (see app/demo/*).
// Do not hand-author recipe data here — run the generator against the DB instead.
import type { Dish } from "@/lib/types";

export const DEMO_DISHES: Dish[] = [];
export const DEMO_TAGS: string[] = [];
export const DEMO_READY: boolean = DEMO_DISHES.length > 0;
