import "server-only";
import { sql } from "@/lib/db";
import {
  CLAUDE_HARNESS_MODELS,
  startClaudeAgentJob,
  pollClaudeAgentJob,
  ClaudeAgentError,
  type PollResult,
} from "@/lib/ingest/claude-agent";
import { buildIngestPrompt } from "@/lib/ingest/prompt";
import { DISH_INPUT_JSON_SCHEMA } from "@/lib/ingest/schema";
import { normalizeEscapedWhitespace } from "@/lib/ingest/sanitize";
import { DishInputSchema } from "@/lib/types";
import { getPantryDefaults } from "@/lib/pantry";
import { languageName } from "@/lib/languages";
import { createDishForUser } from "@/lib/dish-create";
import {
  submitImageBatch,
  pollBatch,
  cancelBatch,
  type BatchRequest,
} from "@/lib/nex-image-batch";
import { DISH_IMAGE_MODEL } from "@/lib/image-model";
import { buildImagePrompt } from "@/lib/image-prompt";
import { uploadDishImage } from "@/lib/image-storage";
import { type ImportRow, type ImageBatch } from "./types";

const CLAUDE_AGENT_BASE_URL =
  process.env.CLAUDE_AGENT_URL ?? "https://nex.tail7f6b96.ts.net:10000";

// Bounds that keep one advance step well under Vercel's 60s function budget and
// keep claude-agent / Nex Image Generator load polite. No hard recipe cap (by
// design) — these just slice the work across polls.
const PARSE_CONCURRENCY = 3; // parse jobs in flight at once
// pollBatch returns the generated bytes inline. Twelve GPT Image 2 results keep
// one completion/apply step inside Vercel's response and duration budgets.
const IMAGE_BATCH_MAX = 12;
const IMAGE_APPLY_SLICE = 12; // image uploads applied per step (~each ≤300ms)
// The browser polls this import every couple of seconds, but GPT Image 2 can
// take minutes — throttle upstream polling independently of client cadence.
const IMAGE_POLL_INTERVAL_MS = 15_000;
const IMAGE_MAX_ATTEMPTS = 80; // ~20 min of polling, then give up (dishes stay imageless)

function token(): string {
  // Routes guard NEX_API_TOKEN presence before calling advance; assert here.
  return process.env.NEX_API_TOKEN ?? "";
}

function dishIdFromKey(key: string): number | null {
  if (!key.startsWith("dish_")) return null;
  const n = Number(key.slice("dish_".length));
  return Number.isFinite(n) ? n : null;
}

/** Persist all mutable fields of an advancing row and release the lock. */
async function saveRow(row: ImportRow): Promise<ImportRow> {
  await sql`
    UPDATE import_jobs SET
      status        = ${row.status},
      detect_job_id = ${row.detect_job_id},
      chunks        = ${JSON.stringify(row.chunks)}::jsonb,
      image_batches = ${JSON.stringify(row.image_batches)}::jsonb,
      error         = ${row.error},
      locked_until  = NULL,
      updated_at    = now()
    WHERE id = ${row.id}
  `;
  return row;
}

/**
 * Advance a LOCKED import row exactly one bounded step, persist it, release the
 * lock, and return the updated row. The caller must already hold the row's lock
 * (locked_until). Each phase does a slice of work; the browser's next poll
 * continues from the persisted state, so the import survives navigation.
 */
export async function advanceImport(row: ImportRow): Promise<ImportRow> {
  switch (row.status) {
    case "detecting":
      return advanceDetecting(row);
    case "parsing":
      return advanceParsing(row);
    case "imaging":
      return advanceImaging(row);
    default:
      // detected (awaiting confirm), done, failed → nothing to do; just unlock.
      await sql`UPDATE import_jobs SET locked_until = NULL WHERE id = ${row.id}`;
      return row;
  }
}

// ---------- detecting ----------
async function advanceDetecting(row: ImportRow): Promise<ImportRow> {
  if (!row.detect_job_id) {
    row.status = "failed";
    row.error = "detect job missing";
    return saveRow(row);
  }
  let result: PollResult;
  try {
    result = await pollClaudeAgentJob(row.detect_job_id, {
      token: token(),
      baseUrl: CLAUDE_AGENT_BASE_URL,
    });
  } catch {
    return saveRow(row); // transient — retry on next poll
  }
  if (result.status !== "done") {
    if (result.status === "failed") {
      row.status = "failed";
      row.error = result.errorMessage || "detection failed";
    }
    // pending/running → retry on next poll; failed → terminal (set above)
    return saveRow(row);
  }
  // done — pull the recipe chunks out of the structured payload
  const structured = result.structured as { recipes?: unknown } | null;
  const list = Array.isArray(structured?.recipes) ? (structured!.recipes as unknown[]) : [];
  const chunks = list
    .map((r) => {
      const o = (r ?? {}) as Record<string, unknown>;
      const title = typeof o.title === "string" ? o.title.trim() : "";
      const text = typeof o.text === "string" ? o.text.trim() : "";
      return { title, text };
    })
    .filter((r) => r.title || r.text)
    .map((r) => ({
      title: r.title || "Untitled recipe",
      text: r.text || r.title,
      status: "queued" as const,
      image: "pending" as const,
    }));
  if (chunks.length === 0) {
    row.status = "failed";
    row.error = "no recipes found in the document";
    return saveRow(row);
  }
  row.chunks = chunks;
  row.status = "detected";
  return saveRow(row);
}

// ---------- parsing (+ create) ----------
async function advanceParsing(row: ImportRow): Promise<ImportRow> {
  const tok = token();

  // 1) Poll in-flight parse jobs; create a dish for each that finished.
  for (const chunk of row.chunks) {
    if (chunk.status !== "parsing" || !chunk.parseJobId) continue;
    let res: PollResult;
    try {
      res = await pollClaudeAgentJob(chunk.parseJobId, {
        token: tok,
        baseUrl: CLAUDE_AGENT_BASE_URL,
      });
    } catch {
      continue; // transient — retry next poll
    }
    if (res.status !== "done") {
      if (res.status === "failed") {
        chunk.status = "failed";
        chunk.error = res.errorMessage || "parse failed";
      }
      continue; // pending/running → retry next poll
    }
    try {
      const dishId = await createDishFromStructured(res.structured, row.user_id);
      chunk.dishId = dishId;
      chunk.status = "created";
    } catch (err) {
      chunk.status = "failed";
      chunk.error = err instanceof Error ? err.message : "could not create dish";
    }
  }

  // 2) Start new parse jobs up to the concurrency cap.
  let inFlight = row.chunks.filter((c) => c.status === "parsing").length;
  if (inFlight < PARSE_CONCURRENCY && row.chunks.some((c) => c.status === "queued")) {
    const pantryList = Array.from(await getPantryDefaults(row.user_id)).sort();
    const targetLanguage = await targetLang(row.user_id);
    for (const chunk of row.chunks) {
      if (inFlight >= PARSE_CONCURRENCY) break;
      if (chunk.status !== "queued") continue;
      try {
        const prompt = buildIngestPrompt({
          userInput: chunk.text,
          pantryList,
          targetLanguage,
        });
        const job = await startClaudeAgentJob({
          prompt,
          responseSchema: DISH_INPUT_JSON_SCHEMA,
          token: tok,
          baseUrl: CLAUDE_AGENT_BASE_URL,
          model: CLAUDE_HARNESS_MODELS.haiku,
        });
        chunk.parseJobId = job.jobId;
        chunk.status = "parsing";
        inFlight++;
      } catch (err) {
        if (
          err instanceof ClaudeAgentError &&
          (err.code === "queue_full" || err.code === "rate_limited")
        ) {
          break; // back off — leave queued, retry next poll
        }
        chunk.status = "failed";
        chunk.error = err instanceof Error ? err.message : "could not start parse";
      }
    }
  }

  // 3) Transition once every chunk is settled.
  if (row.chunks.every((c) => c.status === "created" || c.status === "failed")) {
    row.status = row.chunks.some((c) => c.status === "created") ? "imaging" : "done";
  }
  return saveRow(row);
}

async function createDishFromStructured(structured: unknown, userId: string): Promise<number> {
  // Repair Haiku's literal-"\n"-instead-of-newline quirk in text fields
  // (recipe/subtitle/ingredient prep) so the method renders as steps. Inline
  // `[label](#index)` references live inside `recipe`; createDishForUser does
  // the index→id rewrite once ingredient ids are assigned.
  normalizeEscapedWhitespace(structured);
  const validated = DishInputSchema.safeParse(structured);
  if (!validated.success) throw new Error("parsed dish failed validation");
  // autoImage:false — the batch importer owns the GPT Image 2 Nex batches.
  const dish = await createDishForUser(validated.data, userId, { autoImage: false });
  return dish.id;
}

async function targetLang(userId: string): Promise<string> {
  const rows = await sql`SELECT default_language FROM users WHERE id = ${userId}`;
  return languageName((rows[0]?.default_language as string | null) ?? null);
}

// ---------- imaging: GPT Image 2 through Nex batch ----------
async function advanceImaging(row: ImportRow): Promise<ImportRow> {
  const token = process.env.NEX_API_TOKEN;
  const pending = row.chunks.filter(
    (c) => c.status === "created" && (c.image ?? "pending") === "pending" && c.dishId != null,
  );
  if (pending.length === 0) {
    row.status = "done";
    return saveRow(row);
  }

  // No Nex API token → finish imageless (each dish is regenerable later via
  // its image button). This is also the local-dev path (no key).
  if (!token) {
    for (const c of pending) c.image = "failed";
    row.status = "done";
    return saveRow(row);
  }

  // Do not apply legacy in-flight Nano Banana/FLUX batches after this
  // migration. Cancel them and resubmit any still-pending dishes explicitly to
  // GPT Image 2. Old rows have no model field, so they take this path too.
  if (
    row.image_batches.some(
      (batch) => !batch.applied && batch.model !== DISH_IMAGE_MODEL,
    )
  ) {
    for (const batch of row.image_batches) {
      if (!batch.applied) await cancelBatch(token, batch.name);
    }
    row.image_batches = [];
  }

  // First imaging step: submit explicit GPT Image 2 batch(es) for every pending
  // dish, regardless of user or import size.
  if (row.image_batches.length === 0) {
    const ids = pending.map((c) => c.dishId as number);
    const dishRows = await sql`
      SELECT id, title, subtitle, image_description
        FROM dishes WHERE id = ANY(${ids}::int[]) AND user_id = ${row.user_id}
    `;
    const byId = new Map(dishRows.map((d) => [d.id as number, d]));
    const batches: ImageBatch[] = [];
    for (let i = 0; i < ids.length; i += IMAGE_BATCH_MAX) {
      const slice = ids.slice(i, i + IMAGE_BATCH_MAX);
      const missing = slice.filter((id) => !byId.has(id));
      for (const id of missing) {
        const chunk = row.chunks.find((candidate) => candidate.dishId === id);
        if (chunk) chunk.image = "failed";
      }
      const requests: BatchRequest[] = slice
        .filter((id) => byId.has(id))
        .map((id) => {
          const d = byId.get(id)!;
          return {
            key: `dish_${id}`,
            prompt: buildImagePrompt({
              title: d.title as string,
              subtitle: (d.subtitle as string | null) ?? null,
              imageDescription: (d.image_description as string | null) ?? null,
            }),
          };
        });
      if (requests.length === 0) continue;
      try {
        const sub = await submitImageBatch(
          token,
          DISH_IMAGE_MODEL,
          `ds-import-${row.id.slice(0, 8)}-${i}`,
          requests,
        );
        batches.push({
          name: sub.name,
          state: sub.state,
          applied: false,
          model: DISH_IMAGE_MODEL,
          dishIds: requests
            .map((request) => dishIdFromKey(request.key))
            .filter((id): id is number => id != null),
        });
      } catch {
        // Couldn't submit this slice → those dishes land imageless.
        for (const id of slice) {
          const c = row.chunks.find((x) => x.dishId === id);
          if (c) c.image = "failed";
        }
      }
    }
    row.image_batches = batches;
    if (batches.length === 0) {
      // every submit failed → nothing left to image
      if (!row.chunks.some((c) => c.status === "created" && (c.image ?? "pending") === "pending")) {
        row.status = "done";
      }
    }
    return saveRow(row);
  }

  // Subsequent steps: poll unapplied batches; apply succeeded results in a slice.
  const now = Date.now();
  let applied = 0;
  for (const batch of row.image_batches) {
    if (batch.applied) continue;
    if (applied >= IMAGE_APPLY_SLICE) break;
    // Throttle upstream polling independently of the browser.
    if (batch.polledAt && now - batch.polledAt < IMAGE_POLL_INTERVAL_MS) continue;
    batch.polledAt = now;
    batch.attempts = (batch.attempts ?? 0) + 1;
    // Bound the wait — give up on a batch that never resolves so the import
    // can finish (its dishes stay imageless, regenerable from the dish). Cancel
    // it so Nex stops retrying its pending requests.
    if (batch.attempts > IMAGE_MAX_ATTEMPTS) {
      await cancelBatch(token, batch.name);
      batch.applied = true;
      for (const dishId of batch.dishIds ?? []) {
        const chunk = row.chunks.find((candidate) => candidate.dishId === dishId);
        if (chunk && (chunk.image ?? "pending") === "pending") {
          chunk.image = "failed";
        }
      }
      continue;
    }
    let polled;
    try {
      polled = await pollBatch(token, batch.name);
    } catch {
      continue; // transient — retry after the throttle interval
    }
    batch.state = polled.state;
    if (polled.state === "BATCH_STATE_FAILED") {
      batch.applied = true;
      for (const dishId of batch.dishIds ?? []) {
        const chunk = row.chunks.find((candidate) => candidate.dishId === dishId);
        if (chunk && (chunk.image ?? "pending") === "pending") {
          chunk.image = "failed";
        }
      }
      continue;
    }
    if (polled.state !== "BATCH_STATE_SUCCEEDED" || !polled.results) continue;

    for (const r of polled.results) {
      if (applied >= IMAGE_APPLY_SLICE) break; // resume on the next poll
      const dishId = dishIdFromKey(r.key);
      if (dishId == null) continue;
      const chunk = row.chunks.find((c) => c.dishId === dishId);
      if (!chunk || (chunk.image ?? "pending") !== "pending") continue; // already settled
      if (r.error || !r.bytes || !r.mime) {
        chunk.image = "failed";
        continue;
      }
      try {
        const imageUrl = await uploadDishImage(dishId, r.bytes, r.mime);
        await sql`
          UPDATE dishes SET image_url = ${imageUrl}, updated_at = now()
           WHERE id = ${dishId} AND user_id = ${row.user_id}
        `;
        chunk.image = "done";
      } catch {
        chunk.image = "failed";
      }
      applied++;
    }

    // Mark the batch applied once none of its result-dishes are still pending.
    const stillPending = polled.results.some((r) => {
      const id = dishIdFromKey(r.key);
      if (id == null) return false;
      const c = row.chunks.find((x) => x.dishId === id);
      return c && (c.image ?? "pending") === "pending";
    });
    if (!stillPending) batch.applied = true;
  }

  // If every batch is settled (applied or given up) but some dishes never got
  // an image, finish them imageless rather than spin forever.
  const allBatchesSettled = row.image_batches.every((b) => b.applied);
  if (allBatchesSettled) {
    for (const c of row.chunks) {
      if (c.status === "created" && (c.image ?? "pending") === "pending") c.image = "failed";
    }
  }
  if (
    allBatchesSettled ||
    !row.chunks.some((c) => c.status === "created" && (c.image ?? "pending") === "pending")
  ) {
    row.status = "done";
  }
  return saveRow(row);
}
