// Standard vocabularies for ingredient units and names.
//
// These are intentionally NOT enforced at the schema level — Zod accepts any
// string. The vocabularies are surfaced as <datalist> autocomplete in the
// admin form and as guidance in CLAUDE.md / AGENTS.md so that the agent
// (and humans) anchor on a consistent set of terms.
//
// If a needed value isn't here, just type it freely — but prefer adding to
// these lists over diverging.

export const STANDARD_UNITS: readonly string[] = [
  // weight
  "g",
  "kg",
  "oz",
  "lb",
  // volume
  "ml",
  "l",
  "tsp",
  "tbsp",
  "cup",
  "fl oz",
  // count
  "piece",
  "clove",
  "wedge",
  "slice",
  "sprig",
  "leaf",
  "head",
  "bulb",
  "stalk",
  "bunch",
  "handful",
  "can",
  "jar",
  "bottle",
  "pack",
  // imprecise
  "pinch",
  "dash",
  "splash",
  "drizzle",
  "to taste",
];

export const STANDARD_INGREDIENTS: readonly string[] = [
  // vegetables
  "onion",
  "red onion",
  "shallot",
  "spring onion",
  "garlic",
  "ginger",
  "carrot",
  "potato",
  "sweet potato",
  "tomato",
  "cherry tomato",
  "cucumber",
  "bell pepper",
  "red pepper",
  "yellow pepper",
  "green pepper",
  "chili",
  "green chili",
  "red chili",
  "lettuce",
  "spinach",
  "kale",
  "rocket",
  "broccoli",
  "cauliflower",
  "cabbage",
  "courgette",
  "aubergine",
  "mushroom",
  "leek",
  "celery",
  "parsnip",
  "beetroot",
  "radish",
  "corn",
  "peas",
  "green bean",
  "French bean",
  "asparagus",
  "butternut squash",
  // fruits
  "apple",
  "orange",
  "lemon",
  "lime",
  "banana",
  "strawberry",
  "blueberry",
  "raspberry",
  "mango",
  "pineapple",
  "peach",
  "pear",
  "grape",
  "avocado",
  "watermelon",
  // herbs
  "basil",
  "parsley",
  "coriander",
  "mint",
  "thyme",
  "rosemary",
  "oregano",
  "sage",
  "dill",
  "chives",
  "bay leaf",
  // spices
  "salt",
  "black pepper",
  "white pepper",
  "cumin",
  "coriander seed",
  "paprika",
  "smoked paprika",
  "chili powder",
  "cayenne",
  "turmeric",
  "cinnamon",
  "nutmeg",
  "garam masala",
  "curry powder",
  "cardamom",
  "clove",
  "fennel seed",
  "mustard seed",
  "star anise",
  "vanilla extract",
  // proteins
  "chicken breast",
  "chicken thigh",
  "chicken wing",
  "whole chicken",
  "beef mince",
  "beef steak",
  "stewing beef",
  "pork mince",
  "pork chop",
  "bacon",
  "sausage",
  "lamb mince",
  "lamb chop",
  "salmon",
  "tuna",
  "cod",
  "prawn",
  "egg",
  "tofu",
  "tempeh",
  "lentil",
  "chickpea",
  "black bean",
  "kidney bean",
  "white bean",
  // dairy
  "milk",
  "butter",
  "unsalted butter",
  "cream",
  "double cream",
  "sour cream",
  "yoghurt",
  "mozzarella",
  "cheddar",
  "parmesan",
  "feta",
  "ricotta",
  "mascarpone",
  "halloumi",
  "cream cheese",
  // pantry
  "plain flour",
  "bread flour",
  "sugar",
  "brown sugar",
  "caster sugar",
  "icing sugar",
  "baking powder",
  "baking soda",
  "yeast",
  "olive oil",
  "sunflower oil",
  "vegetable oil",
  "sesame oil",
  "coconut oil",
  "vinegar",
  "balsamic vinegar",
  "white wine vinegar",
  "soy sauce",
  "fish sauce",
  "oyster sauce",
  "hoisin sauce",
  "sriracha",
  "mustard",
  "dijon mustard",
  "mayonnaise",
  "ketchup",
  "tomato purée",
  "passata",
  "chopped tomato",
  "peeled tomato",
  "coconut milk",
  "vegetable stock",
  "chicken stock",
  "beef stock",
  "pasta",
  "spaghetti",
  "penne",
  "lasagna sheet",
  "rice",
  "basmati rice",
  "jasmine rice",
  "brown rice",
  "arborio rice",
  "noodles",
  "rice noodles",
  "couscous",
  "quinoa",
  "oats",
  "breadcrumbs",
  "panko",
  "bread",
  // nuts & seeds
  "almond",
  "walnut",
  "cashew",
  "peanut",
  "pistachio",
  "hazelnut",
  "pine nut",
  "sesame seed",
  "sunflower seed",
  "pumpkin seed",
  // sweet
  "honey",
  "maple syrup",
  "dark chocolate",
  "milk chocolate",
  "cocoa powder",
];

/**
 * Ingredient names that are auto-marked pantry:true in the admin form.
 * These are things Mirko always has in stock — excluded from shopping lists.
 */
export const PANTRY_DEFAULTS: ReadonlySet<string> = new Set([
  // water & salt
  "water",
  "salt",
  "black pepper",
  "white pepper",
  // oils
  "olive oil",
  "sunflower oil",
  "vegetable oil",
  "sesame oil",
  "coconut oil",
  // baking
  "plain flour",
  "bread flour",
  "baking powder",
  "baking soda",
  "sugar",
  "caster sugar",
  "brown sugar",
  "icing sugar",
  // vinegars & sauces
  "vinegar",
  "balsamic vinegar",
  "white wine vinegar",
  "soy sauce",
  "fish sauce",
  "sriracha",
  "mustard",
  "ketchup",
  "tomato purée",
]);
