// Generates lib/demo/dishes.ts from ~20 of the seed owner's real recipes.
//
// Usage (run when the DB is reachable):
//   DATABASE_URL=postgres://... SEED_OWNER_EMAIL=you@example.com \
//     npx tsx scripts/build-demo-snapshot.ts
//
// Selects public dishes that have an image, a method, and ingredients, spread
// across tags for variety. Strips `notes` and `imageDescription` (private).
// Idempotent — re-run any time to refresh the demo.
//
// The /demo routes stay dormant (404) until lib/demo/dishes.ts is populated,
// reviewed, and committed. This generator is an explicit content-release step,
// not part of the normal build.

import { writeFileSync } from "node:fs";
import { neon } from "@neondatabase/serverless";
import { rowToDish, type Dish } from "../lib/types.ts";

const LIMIT = 20;

async function main() {
  const url = process.env.DATABASE_URL;
  const owner = (process.env.SEED_OWNER_EMAIL ?? "").trim().toLowerCase();
  if (!url) throw new Error("DATABASE_URL is not set");
  if (!owner) throw new Error("SEED_OWNER_EMAIL is not set");
  const sql = neon(url);

  const rows = await sql`
    SELECT d.*,
      (SELECT MAX(cooked_at) FROM cook_log WHERE dish_id = d.id) AS last_cooked_at,
      (SELECT COUNT(*)       FROM cook_log WHERE dish_id = d.id) AS cook_count,
      (SELECT AVG(rating)::float FROM cook_log WHERE dish_id = d.id AND rating IS NOT NULL) AS avg_rating,
      (SELECT COUNT(*)           FROM cook_log WHERE dish_id = d.id AND rating IS NOT NULL) AS rating_count
    FROM dishes d
    JOIN users u ON u.id = d.user_id
    WHERE u.email = ${owner}
      AND d.public = true
      AND d.image_url IS NOT NULL
      AND d.recipe IS NOT NULL
      AND jsonb_array_length(d.ingredients) > 0
    ORDER BY (d.favorite)::int DESC,
             COALESCE((SELECT AVG(rating)::float FROM cook_log WHERE dish_id = d.id AND rating IS NOT NULL), 0) DESC,
             (SELECT COUNT(*) FROM cook_log WHERE dish_id = d.id) DESC,
             d.updated_at DESC
  `;

  // Greedy pick for tag variety: prefer dishes that introduce a new tag, then
  // backfill with the rest in score order, up to LIMIT.
  const all = rows.map(rowToDish);
  const seenTags = new Set<string>();
  const picked: Dish[] = [];
  const rest: Dish[] = [];
  for (const r of all) {
    const fresh = r.tags.some((t) => !seenTags.has(t));
    if (fresh && picked.length < LIMIT) {
      r.tags.forEach((t) => seenTags.add(t));
      picked.push(r);
    } else {
      rest.push(r);
    }
  }
  for (const r of rest) {
    if (picked.length >= LIMIT) break;
    picked.push(r);
  }

  const demo = picked.slice(0, LIMIT).map((d) => ({ ...d, notes: null, imageDescription: null }));
  const tags = [...new Set(demo.flatMap((d) => d.tags))].sort((a, b) => a.localeCompare(b));

  const body =
`// AUTO-GENERATED by scripts/build-demo-snapshot.ts. Do not hand-edit.
// Source: ${demo.length} public recipes from the seed owner; notes + imageDescription stripped.
import type { Dish } from "@/lib/types";

export const DEMO_DISHES: Dish[] = ${JSON.stringify(demo, null, 2)};
export const DEMO_TAGS: string[] = ${JSON.stringify(tags)};
export const DEMO_READY: boolean = DEMO_DISHES.length > 0;
`;
  writeFileSync(new URL("../lib/demo/dishes.ts", import.meta.url), body);
  console.log(`Wrote lib/demo/dishes.ts — ${demo.length} dishes, ${tags.length} tags.`);
  if (demo.length < LIMIT) {
    console.warn(`Note: only ${demo.length} qualifying dishes found (wanted ${LIMIT}).`);
  }
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
